matrix:
  include:

    ################ Linux Build ################

    - name: Linux
      os: linux
      dist: focal

      services:
        - docker

      addons:
        apt:
          packages:
            - libsdl2-dev
            - libpcap-dev

      install:
        - curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default && unzip butler.zip
        #- curl -L -o zig.tar.xz https://ziglang.org/download/${ZIG_VERSION}/zig-linux-x86_64-${ZIG_VERSION}.tar.xz && tar -xf zig.tar.xz

        #- export PATH=$PATH:${TRAVIS_BUILD_DIR}/zig-linux-x86_64-${ZIG_VERSION}
        - sudo snap install zig --classic --edge

      script:
        - zig build test
        - zig build
        - ./tools/package/itch/package.linux.sh

      after_success:
        - docker run --rm --security-opt seccomp=unconfined -v $(pwd):$(pwd) -w $(pwd) kcov/kcov kcov kcov-out ./zig-cache/o/*/test
        - bash <(curl -s https://codecov.io/bash) -s kcov-out

    ################ OSX Build ################

    - name: OSX
      os: osx
      osx_image: xcode12

      addons:
        homebrew:
          packages:
            - sdl2
            - rpl

      install:
        - curl -L -o butler.zip https://broth.itch.ovh/butler/darwin-amd64/LATEST/archive/default && unzip butler.zip
        - curl -L -o zig.tar.xz https://ziglang.org/download/${ZIG_VERSION}/zig-macos-x86_64-${ZIG_VERSION}.tar.xz && tar -xf zig.tar.xz

        - export PATH=$PATH:${TRAVIS_BUILD_DIR}/zig-macos-x86_64-${ZIG_VERSION}

      script:
        - zig build test
        - zig build
        #- ./tools/package/itch/package.osx.sh

    ################ Windows Build ################

    - name: Windows
      os: windows

      install:
        - curl -L -o butler.zip https://broth.itch.ovh/butler/windows-amd64/LATEST/archive/default && unzip butler.zip
        - curl -L -o sdl.zip https://www.libsdl.org/release/SDL2-devel-${SDL2_WINDOWS_VERSION}-VC.zip && 7z x sdl.zip
        - curl -L -o zig.zip https://ziglang.org/download/0.7.1/zig-windows-x86_64-0.7.1.zip && unzip zig.zip

        - export PATH=$PATH:${TRAVIS_BUILD_DIR}/zig-windows-x86_64-${ZIG_VERSION}
        - export SDL_PATH="${TRAVIS_BUILD_DIR}/SDL2-${SDL2_WINDOWS_VERSION}"

      script:
        - zig build test -Dwindows=true -Dsdl-path=${SDL_PATH}
        - zig build -Dwindows=true -Dsdl-path=${SDL_PATH}
        #- ./tools/package/itch/package.bat

################ Common ################

language: minimal

env:
  - ZIG_VERSION=0.7.1 SDL2_WINDOWS_VERSION=2.0.14 VXT_VERSION=0.6.1

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  - export PATH=$TRAVIS_BUILD_DIR:$PATH
  - export FULL_VERSION=${VXT_VERSION}.${TRAVIS_BUILD_ID}

before_script:
  - zig version

deploy:
  provider: script
  skip_cleanup: true
  script: bash tools/package/itch/push.sh
  on:
    all_branches: true
    #condition: $TRAVIS_BRANCH =~ ^(edge|release)$ && $TRAVIS_OS_NAME != osx
    condition: $TRAVIS_BRANCH == main && $TRAVIS_OS_NAME == linux