matrix:
  include:

    ################ Linux Build ################

    - name: Linux
      os: linux
      #dist: focal

      addons:
        apt:
          packages:
            - xz-utils
            - libsdl2-dev
            - libpcap-dev

      install:
        - curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default && unzip butler.zip
        - curl -L -o zig.tar.xz https://ziglang.org/download/${ZIG_VERSION}/zig-linux-x86_64-${ZIG_VERSION}.tar.xz && tar -xf zig.tar.xz

      script:
        - ${TRAVIS_BUILD_DIR}/zig-linux-x86_64-${ZIG_VERSION}/zig build
        #- ./tools/package/itch/package.linux.sh

    ################ OSX Build ################

    - name: OSX
      os: osx
      #osx_image: xcode12

      addons:
        homebrew:
          packages:
            - sdl2
            - rpl

      install:
        - curl -L -o butler.zip https://broth.itch.ovh/butler/darwin-amd64/LATEST/archive/default && unzip butler.zip
        - curl -L -o zig.tar.xz https://ziglang.org/download/${ZIG_VERSION}/zig-macos-x86_64-${ZIG_VERSION}.tar.xz && tar -xf zig.tar.xz

      script:
        - ${TRAVIS_BUILD_DIR}/zig-linux-x86_64-${ZIG_VERSION}/zig build
        #- ./tools/package/itch/package.osx.sh

    ################ Windows Build ################

    - name: Windows
      os: windows

      install:
        - curl -L -o butler.zip https://broth.itch.ovh/butler/windows-amd64/LATEST/archive/default && unzip butler.zip
        - curl -L -o sdl.tar.gz https://www.libsdl.org/release/SDL2-devel-${SDL2_WINDOWS_VERSION}-VC.zip && 7z x sdl.zip
        - curl -L -o zig.zip https://ziglang.org/download/0.7.1/zig-windows-x86_64-0.7.1.zip && unzip zig.zip

      script:
        - ${TRAVIS_BUILD_DIR}/zig-windows-x86_64-${ZIG_VERSION}/zig build -Dwindows=true -Dsdl-path=${TRAVIS_BUILD_DIR}/SDL2-${SDL2_WINDOWS_VERSION}
        #- ./tools/package/itch/package.bat

################ Common ################

language: generic

env:
  - ZIG_VERSION=0.7.1 SDL2_WINDOWS_VERSION=2.0.14 VXT_VERSION=0.6.1

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  - export PATH=$TRAVIS_BUILD_DIR:$PATH

before_script:
  - export FULL_VERSION=${VXT_VERSION}.${TRAVIS_BUILD_ID}
  #- go generate ./...
  #- cd bios/pcxtbios/build && go run build.go && cd ${TRAVIS_BUILD_DIR}
  #- go test -race -coverprofile coverage.txt -covermode atomic ./...
  #- bash <(curl -s https://codecov.io/bash)

#deploy:
#  provider: script
#  skip_cleanup: true
#  script: bash tools/package/itch/push.sh
#  on:
#    all_branches: true
#    condition: $TRAVIS_BRANCH =~ ^(edge|release)$ && $TRAVIS_OS_NAME != osx