matrix:
  include:

    ################ Linux Build ################

    - name: Linux
      os: linux
      dist: focal

      addons:
        apt:
          packages:
            - xz-utils
            - libsdl2-dev
            - libpcap-dev

      install:
        - curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default && unzip butler.zip
        - curl -L -o zig.tar.xz https://ziglang.org/download/${ZIG_VERSION}/zig-linux-x86_64-${ZIG_VERSION}.tar.xz && tar -xf zig.tar.xz

        - export PATH=${TRAVIS_BUILD_DIR}/zig-linux-x86_64-${ZIG_VERSION}

      script:
        - zig build
        #- ./tools/package/itch/package.linux.sh

    ################ OSX Build ################

    - name: OSX
      os: osx
      osx_image: xcode12

      addons:
        homebrew:
          packages:
            - sdl2
            - rpl

      install:
        - curl -L -o butler.zip https://broth.itch.ovh/butler/darwin-amd64/LATEST/archive/default && unzip butler.zip

      script:
        - go build -tags sdl,pcap,static -ldflags "-s -w"
        - ./tools/package/itch/package.osx.sh

    ################ Windows Build ################

    - name: Windows
      os: windows

      install:
        - curl -L -o butler.zip https://broth.itch.ovh/butler/windows-amd64/LATEST/archive/default && unzip butler.zip
        - curl -L -o sdl.tar.gz https://www.libsdl.org/release/SDL2-devel-2.0.10-mingw.tar.gz && 7z x sdl.tar.gz && 7z x sdl.tar

        - export C_INCLUDE_PATH=${TRAVIS_BUILD_DIR}/SDL2-2.0.10/x86_64-w64-mingw32/include
        - export LIBRARY_PATH=${TRAVIS_BUILD_DIR}/SDL2-2.0.10/x86_64-w64-mingw32/lib

        - go get github.com/akavel/rsrc

      script:
        - rsrc -ico=doc/icon/icon.ico -arch=amd64
        - go build -tags sdl,pcap,static -ldflags "-s -w"
        - ./tools/package/itch/package.bat

################ Common ################

language: generic

env:
  - ZIG_VERSION=0.7.1
  - VXT_VERSION=0.6.1

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  - export PATH=$TRAVIS_BUILD_DIR:$PATH

before_script:
  - export FULL_VERSION=${VXT_VERSION}.${TRAVIS_BUILD_ID}
  #- go generate ./...
  #- cd bios/pcxtbios/build && go run build.go && cd ${TRAVIS_BUILD_DIR}
  #- go test -race -coverprofile coverage.txt -covermode atomic ./...
  #- bash <(curl -s https://codecov.io/bash)

#deploy:
#  provider: script
#  skip_cleanup: true
#  script: bash tools/package/itch/push.sh
#  on:
#    all_branches: true
#    condition: $TRAVIS_BRANCH =~ ^(edge|release)$ && $TRAVIS_OS_NAME != osx